### ISSUE TITLE
main_https.py not launching - unexpected indent

### ISSUE THREAD

**Issue by Tekuzo** [Gerschel/comfyui-enable-tls#1]
I had installed and used the ComfyUI-enable-tls and was using it successfully for several weeks and it seems to have just stopped working. It is giving an error about an unexpected indent.

```
Total VRAM 8176 MB, total RAM 32035 MB
Set vram state to: NORMAL_VRAM
/home/tekuzo/ComfyUI/sdxl/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Device: cuda:0 AMD Radeon RX 6600 : 
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Loading custom server.py
Traceback (most recent call last):
  File "/home/tekuzo/ComfyUI/main_https.py", line 28, in <module>
    exec(code_to_exec)
  File "<string>", line 1
    if args.windows_standalone_build:
IndentationError: unexpected in
```

I have attempted to completely remove and re-install comfyUI, follwing the official instructions to get it working the last time on my AMD GPU.

Currently the python main.py will launch the unencrypted version, but the main_https.py doesn't execute.
The output from the main.py is

```
Total VRAM 8176 MB, total RAM 32035 MB
Set vram state to: NORMAL_VRAM
/home/tekuzo/ComfyUI/sdxl/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Device: cuda:0 AMD Radeon RX 6600 : 
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by Jasonlin00** [comment]
same error

**Comment by ARarGithub** [comment]
I fixed it.

```python
import textwrap

code_to_exec = textwrap.dedent("".join(main_file_lines[start_line - 1:])).replace("http://", "https://").replace("ws://", "wss://")
exec(code_to_exec)
```

**Comment by RubenGarcia** [comment]
I am also affected. @ARarGithub's fix did not work for me.
There seems to be an off-by-one error in the main detecting code:
```
code_to_exec: 
----
    return asyncio_loop, prompt_server, start_all


if __name__ == "__main__":
    # Running directly, just start ComfyUI.
    logging.info("Python version: {}".format(sys.version))
    logging.info("ComfyUI version: {}".format(comfyui_version.__version__))

    if sys.version_info.major == 3 and sys.version_info.minor < 10:
        logging.warning("WARNING: You are using a python version older than 3.10, please upgrade to a newer one. 3.12 and above is recommended.")

    event_loop, _, start_all_func = start_comfyui()
    try:
        x = start_all_func()
        app.logger.print_startup_warnings()
        event_loop.run_until_complete(x)
    except KeyboardInterrupt:
        logging.info("\nStopped server")

    cleanup_temp()

----
```

**Comment by RubenGarcia** [comment]
Probably an off-by-one, adding +1.

**Comment by RubenGarcia** [comment]
With +1, I now get
```
Traceback (most recent call last):
  File "/users/mnmex/garcia/gpu/c/ComfyUI/nodes.py", line 2216, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/users/mnmex/garcia/gpu/c/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 12, in <module>
    import manager_server  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^
  File "/users/mnmex/garcia/gpu/c/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 39, in <module>
    routes = PromptServer.instance.routes
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'PromptServer' has no attribute 'instance'

Cannot import /users/mnmex/garcia/gpu/c/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: type object 'PromptServer' has no attribute 'instance'

```

**Comment by RubenGarcia** [comment]
https://github.com/Gerschel/comfyui-enable-tls/pull/3 fixes the unexpected indent issue, but the PromptServer.instance issue still needs to be addressed.

@ARarGithub, did you manage to fix this locally?
